version: 1
accounts:
- name: alice
  coins:
  - 200000000uandean
  - 100000000uusd
- name: bob
  coins:
  - 100000000uandean
  - 100000000uusd
faucet:
  name: bob
  coins:
  - 100000uandean
  - 100000uusd
validators:
- name: alice
  bonded: 100000000uandean
genesis:
  chain_id: andean-arabica-1
  app_state:
    staking:
      params:
        bond_denom: "uandean"
    mint:
      params:
        mint_denom: "uandean"
    crisis:
      constant_fee:
        denom: "uandean"
    gov:
      params:
        min_deposit:
        - denom: "uandean"
          amount: "10000000"
        expedited_min_deposit:
        - denom: "uandean"
          amount: "50000000"
        voting_period: 120s
        expedited_voting_period: 60s